version: "3.8"

services:
  api:
    build:
      context: ./
      target: release
    ports:
      - 5150:5150

  worker:
    build:
      context: ./
      target: release

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379
