version: "3.8"

volumes:
  postgres:
  rabbit:
  redis:

services:
  api:
    image: localhost/snagem:latest
    command: snagem server --host=0.0.0.0 --port=5150
    depends_on:
      - worker
    environment:
      LOG_LEVEL: WARNING
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SQLALCHEMY_URL: postgresql+psycopg://snagem:snagem@postgres:5432/snagem
    restart: unless-stopped

  worker:
    image: localhost/snagem:latest
    command: snagem worker
    depends_on:
      - postgres
      - redis
    environment:
      LOG_LEVEL: WARNING
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SQLALCHEMY_URL: postgresql+psycopg://snagem:snagem@postgres:5432/snagem
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: snagem
      POSTGRES_USER: snagem
      POSTGRES_PASSWORD: snagem
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    restart: unless-stopped
    volumes:
      - redis:/data
