# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3.8"

volumes:
  postgres:
  rabbit:
  redis:

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_DB: snagem
      POSTGRES_USER: snagem
      POSTGRES_PASSWORD: snagem
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.10.2-management
    environment:
      RABBITMQ_DEFAULT_USER: snagem
      RABBITMQ_DEFAULT_PASS: snagem
      RABBITMQ_DIST_PORT: 25672
      RABBITMQ_NODE_IP_ADDRESS: 0.0.0.0
      RABBITMQ_NODE_PORT: 5672
    volumes:
      - rabbit:/var/lib/rabbitmq/snagem

  # TODO: https://redis.io/docs/manual/security/
  # TODO: https://redis.io/docs/manual/persistence/
  # TODO: https://redis.io/docs/manual/replication/
  # TODO: https://redis.io/docs/manual/scaling/
  redis:
    image: redis:7.0.0
    volumes:
      - redis:/data

  snagd:
    image: localhost/snagem:latest
    command: snagd --host=0.0.0.0
    depends_on:
      - snagd_worker
    environment:
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://snagem:snagem@rabbit:5672
      SQLALCHEMY_URL: postgresql+psycopg://snagem:snagem@postgres:5432/snagem

  snagd_worker:
    image: localhost/snagem:latest
    command: snagd-worker
    depends_on:
      - rabbit
      - redis
      - postgres
    environment:
      CELERY_BROKER_URL: amqp://snagem:snagem@rabbit:5672
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SQLALCHEMY_URL: postgresql+psycopg://snagem:snagem@postgres:5432/snagem
