# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3.8"

services:
  api:
    build:
      context: ./
      target: release
    ports:
      - 5150:5150

  api_worker:
    build:
      context: ./
      target: release

  postgres:
    ports:
      - 5432:5432

  rabbit:
    ports:
      - 5672:5672
      - 25672:25672

  redis:
    ports:
      - 6379:6379
