# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3.7"

volumes:
  postgres:
  rabbit:
  redis:
  snagem:

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: snagem
      POSTGRES_USER: snagem
      POSTGRES_PASSWORD: snagem
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.9.14-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: snagem
      RABBITMQ_DEFAULT_PASS: snagem
      RABBITMQ_DIST_PORT: 25672
      RABBITMQ_MNESIA_DIR: snagem
      RABBITMQ_NODE_IP_ADDRESS: 0.0.0.0
      RABBITMQ_NODE_PORT: 5672
    volumes:
      - rabbit:/var/lib/rabbitmq/snagem

  # TODO: https://redis.io/docs/manual/security/
  # TODO: https://redis.io/docs/manual/persistence/
  # TODO: https://redis.io/docs/manual/replication/
  # TODO: https://redis.io/docs/manual/scaling/
  redis:
    image: redis:6.2.6-alpine
    environment:
      PLACEHOLDER: wewlad
    volumes:
      - redis:/data

  snagem:
    build:
      context: ./
      target: release
    command: snagd --host 0.0.0.0 --port 8080
    depends_on:
      - worker
    environment:
      SNAGEM_BROKER_URL: redis://localhost:5678
      SNAGEM_BACKEND_URL: amqp://snagem:snagem@rabbit:5672
      SNAGEM_DATABASE_URL: postgres+psycopg2://snagem:snagem@postgres:5432/snagem

  worker:
    build:
      context: ./
      target: release
    command: celery worker -A snagd.worker -l info -Q main-queue -c 1
    depends_on:
      - rabbit
      - redis
      - postgres
    environment:
      SNAGEM_BROKER_URL: redis://localhost:5678
      SNAGEM_BACKEND_URL: amqp://snagem:snagem@rabbit:5672
      SNAGEM_DATABASE_URL: postgres+psycopg2://snagem:snagem@postgres:5432/snagem
