# SPDX-License-Identifier: AGPL-3.0-or-later

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.7"]

[tool.poetry]
authors = ["Johnathan C. Maudlin <jcmdln@gmail.com>"]
description = ""
license = "MIT"
name = "snagem"
packages = [{ include = "snagctl" }, { include = "snagd" }]
readme = "README.md"
repository = "https://github.com/jcmdln/snagem"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.7"

alembic = "^1.7.6"
celery = { version = "^5.2.3", extras = ["redis"] }
click = "^8.0.4"
datetime = "^4.4"
fastapi = "^0.74.1"
humanfriendly = "^10.0"
itsdangerous = "^2.1.0"
jinja2 = "^3.0.3"
orjson = "^3.6.7"
psycopg2 = "^2.9.3"
python-dateutil = "2.8.2"
python-multipart = "0.0.5"
pyyaml = "^6.0"
requests = "^2.27.1"
sqlalchemy = "^1.4.31"
uvicorn = "^0.17.5"
youtube_dl = "*"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^22.1.0"
coverage = "^6.3.1"
flake8 = "^4.0.1"
flake8-black = "^0.2.4"
flake8-docstrings = "^1.6.0"
flake8-isort = "^4.0.2"
isort = "^5.10.1"
jedi-language-server = "^0.35.1"
mccabe = "^0.6.1"
mypy = ">=0.931"
pyls-flake8 = "^0.4.0"
pyls-isort = "^0.2.2"
pylsp-mypy = "^0.5.7"
pylsp-rope = "^0.1.8"
pytest = "^7.0.0"
python-lsp-black = "^1.1.0"
python-lsp-server = { version = "^1.3.3", extras = [
    "mccabe",
    "pycodestyle",
    "pydocstyle",
    "pyflakes",
    "rope",
] }
sqlalchemy-stubs = "^0.4"
tox = "^3.24.5"
types-click = "^7.1.8"
types-cryptography = "^3.3.15"
types-humanfriendly = "^9.2.4"
types-itsdangerous = "^1.1.6"
types-jinja2 = "^2.11.9"
types-orjson = "^3.6.2"
types-pyyaml = "^6.0.4"
types-redis = "^4.1.17"
types-requests = "^2.27.11"
types-sqlalchemy = "^1.4.18"

[tool.poetry.scripts]
snagctl = "snagctl.main:main"
snagd = "snagd.main:main"

#
# Extras
#

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
lines_between_types = 1
profile = "black"
remove_redundant_aliases = true
wrap_length = 99

[tool.mypy]
strict = true
# Disable specific '--strict' checks
disallow_any_generics = false
disallow_subclassing_any = false
disallow_untyped_calls = false
ignore_missing_imports = true
