# SPDX-License-Identifier: AGPL-3.0-or-later

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
    "poetry-core>=1.0.7",
]

[tool.poetry]
name = "snagem"
version = "0.1.0"
description = ""
license = "MIT"
readme = "README.md"
repository = "https://github.com/jcmdln/snagem"
authors = ["Johnathan C. Maudlin <jcmdln@gmail.com>"]
packages = [
    { include = "snagctl" },
    { include = "snagd" },
]

[tool.poetry.dependencies]
python = "^3.7"
alembic = "^1.7.6"
celery = { version = "^5.2.3", extras = ["redis"] }
click = "^8.0.3"
datetime = "^4.4"
fastapi = { version = "^0.73", extras = ["all"] }
humanfriendly = "^10.0"
psycopg = "^3.0.7"
sqlalchemy = { version = "^1.4.31", extras = ["mypy"] }
youtube_dl = "*"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^22.1.0"
coverage = "^6.3.1"
flake8 = "^4.0.1"
flake8-black = "^0.2.4"
flake8-docstrings = "^1.6.0"
flake8-isort = "^4.0.2"
isort = "^5.10.1"
jedi-language-server = "^0.35.1"
mccabe = "^0.6.1"
mypy = ">=0.931"
pyls-flake8 = "^0.4.0"
pyls-isort = "^0.2.2"
pylsp-mypy = "^0.5.7"
pylsp-rope = "^0.1.8"
pytest = "^7.0.0"
python-lsp-black = "^1.1.0"
python-lsp-server = { version = "^1.3.3", extras = [
    "mccabe",
    "pycodestyle",
    "pydocstyle",
    "pyflakes",
    "rope",
] }
tox = "^3.24.5"

[tool.poetry.scripts]
snagctl = "snagctl.main:main"
snagd = "snagd.main:main"

#
# Extras
#

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
lines_between_types = 1
profile = "black"
remove_redundant_aliases = true
wrap_length = 99

[tool.mypy]
# --strict
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
# --strict end
# disallow_any_generics = false
ignore_missing_imports = true
