# SPDX-License-Identifier: AGPL-3.0-or-later
---
name: Lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yaml
      - poetry.lock
      - pyproject.toml
      - setup.cfg
      - snagctl/**/*.py
      - snagd/**/*.py
      - snagd/db/alembic/script.py.mako
  push:
    paths:
      - .github/workflows/lint.yaml
      - poetry.lock
      - pyproject.toml
      - setup.cfg
      - snagctl/**/*.py
      - snagd/**/*.py
      - snagd/db/alembic/script.py.mako
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - name: bandit
          - name: flake8
          - name: mypy

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install system package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git libpq-dev libsqlite3-dev python3-dev python3-wheel

      # FIXME: poetry>=1.2,<2 once released
      - name: Install python package dependencies
        run: |
          pip install poetry==1.2.0b1
          poetry install --only tox

      - name: Run ${{ matrix.name }}
        run: poetry run tox -e ${{ matrix.name }}
