# SPDX-License-Identifier: AGPL-3.0-or-later
---
name: Lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yaml
      - poetry.lock
      - pyproject.toml
      - setup.cfg
      - snag/**/*.py
      - snagd/**/*.py
      - snagd/db/alembic/script.py.mako
  push:
    paths:
      - .github/workflows/lint.yaml
      - poetry.lock
      - pyproject.toml
      - setup.cfg
      - snag/**/*.py
      - snagd/**/*.py
      - snagd/db/alembic/script.py.mako
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        linter: ["bandit", "flake8", "mypy"]
        # https://endoflife.date/python
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]

    name: ${{ matrix.linter }}-${{ matrix.python-version }}
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            poetry.lock

      - name: Setup venv cache
        uses: actions/cache@v3
        id: cache-venv
        with:
          key: venv-${{ matrix.linter }}-${{ hashFiles('poetry.lock') }}
          path: .venv

      - name: Setup Tox cache
        uses: actions/cache@v3
        id: cache-tox
        with:
          key: tox-${{ matrix.linter }}-${{ hashFiles('poetry.lock') }}
          path: .tox/${{ matrix.linter }}

      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install -y git libpq-dev libsqlite3-dev

      # TODO: poetry>=1.2,<2 once released
      - name: Install Poetry
        run: pip install git+https://github.com/python-poetry/poetry.git@ac49097

      - name: Install ${{ matrix.linter }}
        run: poetry install --only tox

      - name: Run ${{ matrix.linter }}
        run: poetry run tox -e ${{ matrix.linter }}
