---
name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - name: bandit
          - name: flake8
          - name: mypy

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install system package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git libpq-dev libsqlite3-dev python3-dev python3-wheel

      - name: Install python package dependencies
        run: |
          pip install poetry tox

      - name: Run ${{ matrix.name }}
        run: |
          poetry run tox -e ${{ matrix.name }}
